### ISSUE TITLE
Image component not rendering properly

### ISSUE THREAD

**Issue by mjsevilla** [karatechops/create-react-app-grommet#1]
Hiya @karatechops, I started building on top of this repo and I'm trying to replicate the [Primary Page Template](http://grommet-primary-page-vanilla.grmmt.co/). I copied the code for the `Hero` component ([found here](https://github.com/grommet/grommet-primary-page)) and then updated the necessary properties.

### Resulting Behavior
![capture](https://user-images.githubusercontent.com/7141345/33966348-2a7659dc-e014-11e7-8c1d-2f0c9df39d6a.PNG)

### Code
![capture2](https://user-images.githubusercontent.com/7141345/33966363-30d45c5c-e014-11e7-8e79-5b44015871dd.PNG)

I'm not sure why I'm having issues finding the image. This issue persists even outside of the `Hero` component. If you follow the file structure, I'm referencing the image properly. Am I missing something here?

**Comment by karatechops** [comment]
Hey @mjsevilla, if you'd like to use images without importing them you can place them in the `public ` folder. Placing your `hero_splash.jpg` image in the public folder would change your Hero src prop to `src='hero_splash.jpg'`. You can find more information in the [CRA docs](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-images-fonts-and-files). 

Personally I would lean towards housing the images in the component folder and importing them through Webpack. Running external assets through Webpack has a lot of benefits, one being that you could run an image optimizer plugin in Webpack.

**Comment by mjsevilla** [comment]
Oh my gosh, I can't believe I forgot to import the image that way! I was so focused on following the Grommet docs that I didn't think about importing it properly. It's working now, thanks!
